
CREATE TABLE IF NOT EXISTS `zz_address_tx_000` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_001` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_002` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_003` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_004` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_005` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_006` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_007` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_008` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_009` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_010` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_011` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_012` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_013` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_014` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_015` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_016` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_017` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_018` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_019` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_020` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_021` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_022` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_023` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_024` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_025` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_026` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_027` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_028` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_029` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_030` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_031` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_032` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_033` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_034` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_035` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_036` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_037` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_038` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_039` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_040` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_041` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_042` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_043` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_044` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_045` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_046` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_047` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_048` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_049` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_050` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_051` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_052` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_053` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_054` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_055` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_056` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_057` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_058` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_059` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_060` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_061` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_062` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_063` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_064` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_065` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_066` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_067` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_068` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_069` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_070` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_071` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_072` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_073` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_074` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_075` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_076` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_077` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_078` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_079` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_080` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_081` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_082` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_083` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_084` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_085` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_086` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_087` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_088` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_089` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_090` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_091` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_092` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_093` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_094` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_095` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_096` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_097` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_098` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_099` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_100` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_101` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_102` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_103` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_104` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_105` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_106` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_107` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_108` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_109` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_110` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_111` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_112` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_113` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_114` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_115` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_116` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_117` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_118` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_119` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_120` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_121` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_122` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_123` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_124` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_125` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_126` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_127` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_128` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_129` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_130` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_131` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_132` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_133` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_134` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_135` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_136` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_137` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_138` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_139` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_140` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_141` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_142` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_143` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_144` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_145` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_146` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_147` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_148` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_149` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_150` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_151` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_152` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_153` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_154` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_155` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_156` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_157` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_158` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_159` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_160` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_161` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_162` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_163` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_164` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_165` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_166` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_167` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_168` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_169` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_170` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_171` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_172` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_173` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_174` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_175` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_176` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_177` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_178` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_179` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_180` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_181` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_182` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_183` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_184` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_185` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_186` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_187` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_188` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_189` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_190` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_191` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_192` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_193` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_194` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_195` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_196` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_197` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_198` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_199` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_200` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_201` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_202` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_203` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_204` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_205` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_206` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_207` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_208` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_209` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_210` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_211` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_212` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_213` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_214` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_215` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_216` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_217` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_218` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_219` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_220` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_221` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_222` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_223` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_224` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_225` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_226` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_227` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_228` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_229` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_230` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_231` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_232` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_233` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_234` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_235` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_236` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_237` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_238` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_239` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_240` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_241` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_242` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_243` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_244` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_245` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_246` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_247` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_248` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_249` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_250` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_251` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_252` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_253` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_254` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;


CREATE TABLE IF NOT EXISTS `zz_address_tx_255` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `hash` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  `address` varchar(64) NOT NULL DEFAULT '' COMMENT '',
  PRIMARY KEY (`id`),
  KEY (`address`)
) ENGINE=InnoDB AUTO_INCREMENT=1000 DEFAULT CHARSET=utf8;

